#!/bin/bash

# Script para configurar las variables de entorno en Vercel

echo "=== CONFIGURACIÓN DE VARIABLES DE ENTORNO EN VERCEL ==="
echo ""
echo "Ve a: https://vercel.com/summerkaos-projects/healthai-saas/settings/environment-variables"
echo ""
echo "Añade o actualiza las siguientes variables:"
echo ""
echo "1. NEXT_PUBLIC_SUPABASE_URL"
echo "   Valor: https://fulxozhozkeovsdvwjbl.supabase.co"
echo "   Entornos: Production, Preview, Development"
echo ""
echo "2. NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Valor: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bHhvemhvemtlb3ZzZHZ3amJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTM4MjQsImV4cCI6MjA2NzY2OTgyNH0.UWsV9DGCE-_pYRO_N2sdohmP5aAdFFl_BFdCnU_jvZE"
echo "   Entornos: Production, Preview, Development"
echo ""
echo "3. SUPABASE_SERVICE_ROLE_KEY"
echo "   Valor: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bHhvemhvemtlb3ZzZHZ3amJsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjA5MzgyNCwiZXhwIjoyMDY3NjY5ODI0fQ.zILH5KhcglEp6xB6IKrOoUw_oFnrVC6ouSb0uXljhS8"
echo "   Entornos: Production, Preview, Development"
echo ""
echo "IMPORTANTE: Después de guardar las variables, Vercel hará un nuevo deploy automáticamente."
echo ""
echo "Para verificar que las variables están configuradas correctamente, visita:"
echo "https://healthai-saas.vercel.app/api/debug-env"